language: R
sudo: false
cache:
  directories: /tmp/deps
  packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install libopenblas-dev libgsl-dev liblapack-dev
  - pushd /tmp/deps
  - curl -LO https://github.com/DReichLab/AdmixTools/archive/v5.0.tar.gz
  - tar xf v5.0.tar.gz
  - cd AdmixTools-5.0
  - cd src; make clobber; make LDLIBS="-llapack" all; make install; cd ../
  - curl -LO https://www.dropbox.com/s/2m53dharng61ou9/AdmixTools_Example_Data.tar_.gz
  - tar xf AdmixTools_Example_Data.tar_.gz
  - export PATH=$PATH:$PWD/bin
  - popd
  - R -e 'install.packages(c("tidyverse", "MASS", "mgcv"), repos = "http://cran.us.r-project.org")'
after_success:
  - Rscript -e 'covr::codecov()'
